name: dedent
description: Remove any common leading whitespace from every line in text.
version: 1.0.1
repository: https://github.com/abulka/flutter-dedent
license: "PSFL (BSD-style)"

environment:
  sdk: ">=2.12.0 <3.0.0"  # null safety sdk

dependencies:
  quiver: ^3.1.0

dev_dependencies:
  test: ^1.21.1  # dart testing framework

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
